export { default as Login } from './Auth/login';
export { default as Register } from './Auth/register';
export { default as HomePageComponent } from './home-page-component';
export { default as AllUsersPageComponent } from './all-users-page-component';
export { default as HalfTimePageComponent } from './half-time-page-component';
export { default as EndTimePageComponent } from './end-time-page-component';
export { default as ReportPageComponent } from './report-page-component';
export { default as BuildingTypesPageComponent } from './building-types-page-component';
export { default as CottagesPageComponent } from './cottages-page-component';
